// Code generated by mockery v2.20.2. DO NOT EDIT.

package roles

import (
	context "context"
	domain "gitlab.smartcitiesperu.com/smartone/api-core/roles/domain"

	mock "github.com/stretchr/testify/mock"

	paramsdomain "gitlab.smartcitiesperu.com/smartone/api-shared/params/domain"
)

// RoleUseCase is an autogenerated mock type for the RoleUseCase type
type RoleUseCase struct {
	mock.Mock
}

// CreateRole provides a mock function with given fields: ctx, body
func (_m *RoleUseCase) CreateRole(ctx context.Context, body domain.CreateRoleBody) (*string, error) {
	ret := _m.Called(ctx, body)

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateRoleBody) (*string, error)); ok {
		return rf(ctx, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateRoleBody) *string); ok {
		r0 = rf(ctx, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateRoleBody) error); ok {
		r1 = rf(ctx, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteRole provides a mock function with given fields: ctx, roleId
func (_m *RoleUseCase) DeleteRole(ctx context.Context, roleId string) (bool, error) {
	ret := _m.Called(ctx, roleId)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, roleId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, roleId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, roleId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoles provides a mock function with given fields: ctx, pagination
func (_m *RoleUseCase) GetRoles(ctx context.Context, pagination paramsdomain.PaginationParams) ([]domain.Role, *paramsdomain.PaginationResults, error) {
	ret := _m.Called(ctx, pagination)

	var r0 []domain.Role
	var r1 *paramsdomain.PaginationResults
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, paramsdomain.PaginationParams) ([]domain.Role, *paramsdomain.PaginationResults, error)); ok {
		return rf(ctx, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, paramsdomain.PaginationParams) []domain.Role); ok {
		r0 = rf(ctx, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, paramsdomain.PaginationParams) *paramsdomain.PaginationResults); ok {
		r1 = rf(ctx, pagination)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*paramsdomain.PaginationResults)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, paramsdomain.PaginationParams) error); ok {
		r2 = rf(ctx, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateRole provides a mock function with given fields: ctx, roleId, body
func (_m *RoleUseCase) UpdateRole(ctx context.Context, roleId string, body domain.CreateRoleBody) error {
	ret := _m.Called(ctx, roleId, body)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.CreateRoleBody) error); ok {
		r0 = rf(ctx, roleId, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRoleUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewRoleUseCase creates a new instance of RoleUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRoleUseCase(t mockConstructorTestingTNewRoleUseCase) *RoleUseCase {
	mock := &RoleUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
