kind: Service
apiVersion: v1
metadata:
  name: merchants-core-smartone-api-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: merchants-core-smartone
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 80
  type: NodePort
