// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package store_types

import (
	context "context"
	domain "gitlab.smartcitiesperu.com/smartone/api-core/store-types/domain"

	mock "github.com/stretchr/testify/mock"

	paramsdomain "gitlab.smartcitiesperu.com/smartone/api-shared/params/domain"
)

// StoreTypeUseCase is an autogenerated mock type for the StoreTypeUseCase type
type StoreTypeUseCase struct {
	mock.Mock
}

// CreateStoreType provides a mock function with given fields: ctx, body
func (_m *StoreTypeUseCase) CreateStoreType(ctx context.Context, body domain.CreateStoreTypeBody) (*string, error) {
	ret := _m.Called(ctx, body)

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateStoreTypeBody) (*string, error)); ok {
		return rf(ctx, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateStoreTypeBody) *string); ok {
		r0 = rf(ctx, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateStoreTypeBody) error); ok {
		r1 = rf(ctx, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteStoreType provides a mock function with given fields: ctx, storeTypeId
func (_m *StoreTypeUseCase) DeleteStoreType(ctx context.Context, storeTypeId string) (bool, error) {
	ret := _m.Called(ctx, storeTypeId)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, storeTypeId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, storeTypeId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storeTypeId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStoreTypes provides a mock function with given fields: ctx, pagination
func (_m *StoreTypeUseCase) GetStoreTypes(ctx context.Context, pagination paramsdomain.PaginationParams) ([]domain.StoreType, *paramsdomain.PaginationResults, error) {
	ret := _m.Called(ctx, pagination)

	var r0 []domain.StoreType
	var r1 *paramsdomain.PaginationResults
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, paramsdomain.PaginationParams) ([]domain.StoreType, *paramsdomain.PaginationResults, error)); ok {
		return rf(ctx, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, paramsdomain.PaginationParams) []domain.StoreType); ok {
		r0 = rf(ctx, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StoreType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, paramsdomain.PaginationParams) *paramsdomain.PaginationResults); ok {
		r1 = rf(ctx, pagination)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*paramsdomain.PaginationResults)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, paramsdomain.PaginationParams) error); ok {
		r2 = rf(ctx, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateStoreType provides a mock function with given fields: ctx, body, storeTypeId
func (_m *StoreTypeUseCase) UpdateStoreType(ctx context.Context, body domain.UpdateStoreTypeBody, storeTypeId string) error {
	ret := _m.Called(ctx, body, storeTypeId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateStoreTypeBody, string) error); ok {
		r0 = rf(ctx, body, storeTypeId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStoreTypeUseCase creates a new instance of StoreTypeUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStoreTypeUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *StoreTypeUseCase {
	mock := &StoreTypeUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
