definitions:
  domain.CreatePermissionBody:
    properties:
      code:
        description: 'Description: the code of the permission'
        example: REQUIREMENTS_READ
        type: string
      description:
        description: 'Description: the description of the permission'
        example: Permiso para listar requerimientos
        type: string
      id:
        description: 'Description: the id of the permission'
        example: fcdbfacf-8305-11ee-89fd-024255555501
        type: string
      module_id:
        description: 'Description: the module_id of the permission'
        example: cddbfacf-8305-11ee-89fd-024255555502
        type: string
      name:
        description: 'Description: the name of the permission'
        example: Listar requerimientos
        type: string
    required:
    - code
    - description
    - id
    - module_id
    - name
    type: object
  domain.ModuleByPermission:
    properties:
      code:
        description: 'Description: the code of the module'
        example: logistic
        type: string
      description:
        description: 'Description: the description of the module'
        example: Modulo de logística
        type: string
      id:
        description: 'Description: the id of the module'
        example: 739bbbc9-7e93-11ee-89fd-0242ac110016
        type: string
      name:
        description: 'Description: the name of the module'
        example: Logistic
        type: string
    required:
    - code
    - description
    - id
    - name
    type: object
  domain.PaginationResults:
    properties:
      current_page:
        type: integer
      from:
        type: integer
      last_page:
        type: integer
      size_page:
        type: integer
      to:
        type: integer
      total:
        type: integer
    required:
    - current_page
    - last_page
    - size_page
    - total
    type: object
  domain.Permission:
    properties:
      code:
        description: 'Description: the code of the permission'
        example: REQUIREMENTS_READ
        type: string
      created_at:
        description: 'Description: the created_at of the permission'
        example: "2023-11-10 08:10:00"
        type: string
      description:
        description: 'Description: the description of the permission'
        example: Permiso para listar requerimientos
        type: string
      id:
        description: 'Description: the id of the permission'
        example: fcdbfacf-8305-11ee-89fd-024255555501
        type: string
      module:
        $ref: '#/definitions/domain.ModuleByPermission'
      name:
        description: 'Description: the name of the permission'
        example: Listar requerimientos
        type: string
    required:
    - code
    - description
    - id
    - module
    - name
    type: object
  domain.UpdatePermissionBody:
    properties:
      code:
        description: 'Description: the code of the permission'
        example: REQUIREMENTS_READ
        type: string
      description:
        description: 'Description: the description of the permission'
        example: Permiso para listar requerimientos
        type: string
      id:
        description: 'Description: the id of the permission'
        example: fcdbfacf-8305-11ee-89fd-024255555501
        type: string
      name:
        description: 'Description: the name of the permission'
        example: Listar requerimientos
        type: string
    required:
    - code
    - description
    - id
    - name
    type: object
  errorDomain.LayerErr:
    enum:
    - domain
    - infrastructure
    - interface
    - use_case
    type: string
    x-enum-varnames:
    - Domain
    - Infra
    - Interface
    - UseCase
  errorDomain.LevelErr:
    enum:
    - info
    - warning
    - error
    - fatal
    type: string
    x-enum-varnames:
    - LevelInfo
    - LevelWarning
    - LevelError
    - LevelFatal
  errorDomain.SmartError:
    properties:
      code:
        type: string
      description:
        type: string
      error: {}
      function:
        type: string
      httpStatus:
        type: integer
      layer:
        $ref: '#/definitions/errorDomain.LayerErr'
      level:
        $ref: '#/definitions/errorDomain.LevelErr'
      messages:
        items:
          type: string
        type: array
      raw:
        type: string
    type: object
  httpResponse.IdResult:
    properties:
      data:
        example: "201"
        type: string
      status:
        type: integer
    required:
    - data
    - status
    type: object
  httpResponse.StatusResult:
    properties:
      status:
        example: 200
        type: integer
    required:
    - status
    type: object
  rest.deletePermissionResult:
    properties:
      data:
        type: boolean
      status:
        type: integer
    required:
    - data
    - status
    type: object
  rest.permissionsResult:
    properties:
      data:
        items:
          $ref: '#/definitions/domain.Permission'
        type: array
      pagination:
        $ref: '#/definitions/domain.PaginationResults'
      status:
        type: integer
    required:
    - data
    - pagination
    - status
    type: object
info:
  contact: {}
paths:
  /api/v1/core/modules/{moduleId}/permissions:
    get:
      consumes:
      - application/json
      description: Get permissions
      parameters:
      - description: module id
        in: path
        name: moduleId
        type: string
      - description: code
        in: query
        name: code
        type: string
      - description: name
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success Request
          schema:
            $ref: '#/definitions/rest.permissionsResult'
        "500":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorDomain.SmartError'
      security:
      - BearerAuth: []
      summary: Get permissions
      tags:
      - Permissions
    post:
      consumes:
      - application/json
      description: Create a permission
      parameters:
      - description: module id
        in: path
        name: moduleId
        type: string
      - description: Create permission body
        in: body
        name: createPermissionBody
        required: true
        schema:
          $ref: '#/definitions/domain.CreatePermissionBody'
      produces:
      - application/json
      responses:
        "201":
          description: Success Request
          schema:
            $ref: '#/definitions/httpResponse.IdResult'
        "500":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorDomain.SmartError'
      security:
      - BearerAuth: []
      summary: Create a permission
      tags:
      - Permissions
  /api/v1/core/modules/{moduleId}/permissions/{permissionId}:
    delete:
      consumes:
      - application/json
      description: Delete a permission
      parameters:
      - description: module id
        in: path
        name: moduleId
        required: true
        type: string
      - description: permission id
        in: path
        name: permissionId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success Request
          schema:
            $ref: '#/definitions/rest.deletePermissionResult'
        "500":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorDomain.SmartError'
      security:
      - BearerAuth: []
      summary: Delete a permission
      tags:
      - Permissions
    put:
      consumes:
      - application/json
      description: Update a permission
      parameters:
      - description: module id
        in: path
        name: moduleId
        required: true
        type: string
      - description: permission id
        in: path
        name: permissionId
        required: true
        type: string
      - description: Update permission body
        in: body
        name: updatePermissionBody
        required: true
        schema:
          $ref: '#/definitions/domain.UpdatePermissionBody'
      produces:
      - application/json
      responses:
        "200":
          description: Success Request
          schema:
            $ref: '#/definitions/httpResponse.StatusResult'
        "500":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorDomain.SmartError'
      security:
      - BearerAuth: []
      summary: Update a permission
      tags:
      - Permissions
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
