kind: Service
apiVersion: v1
metadata:
  name: permissions-core-smartone-api-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: permissions-core-smartone
  ports:
    - protocol: TCP
      port: 9007
      targetPort: 80
  type: NodePort
