definitions:
  domain.CreateUserTypeBody:
    properties:
      code:
        description: 'Description: the code of the user type'
        example: USER_EXTERNAL
        type: string
      description:
        description: 'Description: the description of the user type'
        example: Usuario externo
        type: string
      enable:
        description: 'Description: the id status the user type'
        example: true
        type: boolean
    required:
    - code
    - description
    type: object
  domain.PaginationResults:
    properties:
      current_page:
        type: integer
      from:
        type: integer
      last_page:
        type: integer
      size_page:
        type: integer
      to:
        type: integer
      total:
        type: integer
    required:
    - current_page
    - last_page
    - size_page
    - total
    type: object
  domain.UpdateUserTypeBody:
    properties:
      code:
        description: 'Description: the code of the user type'
        example: USER_EXTERNAL
        type: string
      description:
        description: 'Description: the description of the user type'
        example: Usuario externo
        type: string
      enable:
        description: 'Description: the id status the user type'
        example: true
        type: boolean
    required:
    - code
    - description
    type: object
  domain.UserType:
    properties:
      code:
        description: 'Description: the code of the user type'
        example: USER_EXTERNAL
        type: string
      created_at:
        description: 'Description: the date of created the user type'
        example: "2023-11-10 08:10:00"
        type: string
      description:
        description: 'Description: the description of the user type'
        example: Usuario externo
        type: string
      enable:
        description: 'Description: the id status the user type'
        example: true
        type: boolean
      id:
        description: 'Description: the id of the user type'
        example: 739bbbc9-7e93-11ee-89fd-0242ac110016
        type: string
    required:
    - code
    - description
    - enable
    - id
    type: object
  errorDomain.LayerErr:
    enum:
    - domain
    - infrastructure
    - interface
    - use_case
    type: string
    x-enum-varnames:
    - Domain
    - Infra
    - Interface
    - UseCase
  errorDomain.LevelErr:
    enum:
    - info
    - warning
    - error
    - fatal
    type: string
    x-enum-varnames:
    - LevelInfo
    - LevelWarning
    - LevelError
    - LevelFatal
  errorDomain.SmartError:
    properties:
      code:
        type: string
      description:
        type: string
      error: {}
      function:
        type: string
      httpStatus:
        type: integer
      layer:
        $ref: '#/definitions/errorDomain.LayerErr'
      level:
        $ref: '#/definitions/errorDomain.LevelErr'
      messages:
        items:
          type: string
        type: array
      raw:
        type: string
    type: object
  httpResponse.IdResult:
    properties:
      data:
        example: "201"
        type: string
      status:
        type: integer
    required:
    - data
    - status
    type: object
  httpResponse.StatusResult:
    properties:
      status:
        example: 200
        type: integer
    required:
    - status
    type: object
  rest.deleteUserTypesResult:
    properties:
      data:
        type: boolean
      status:
        type: integer
    required:
    - data
    - status
    type: object
  rest.userTypesResult:
    properties:
      data:
        items:
          $ref: '#/definitions/domain.UserType'
        type: array
      pagination:
        $ref: '#/definitions/domain.PaginationResults'
      status:
        type: integer
    required:
    - data
    - pagination
    - status
    type: object
info:
  contact: {}
paths:
  /api/v1/core/user_types:
    get:
      consumes:
      - application/json
      description: Get user types
      produces:
      - application/json
      responses:
        "200":
          description: Success Request
          schema:
            $ref: '#/definitions/rest.userTypesResult'
        "500":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorDomain.SmartError'
      security:
      - BearerAuth: []
      summary: Get user types
      tags:
      - User Types
    post:
      consumes:
      - application/json
      description: Create user type
      parameters:
      - description: Create user type body
        in: body
        name: createUserTypeBody
        required: true
        schema:
          $ref: '#/definitions/domain.CreateUserTypeBody'
      produces:
      - application/json
      responses:
        "200":
          description: Success Request
          schema:
            $ref: '#/definitions/httpResponse.IdResult'
        "500":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorDomain.SmartError'
      security:
      - BearerAuth: []
      summary: Create user type
      tags:
      - User Types
  /api/v1/core/user_types/{userTypeId}:
    delete:
      consumes:
      - application/json
      description: Delete user type
      parameters:
      - description: store type id
        in: path
        name: userTypeId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success Request
          schema:
            $ref: '#/definitions/rest.deleteUserTypesResult'
        "500":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorDomain.SmartError'
      security:
      - BearerAuth: []
      summary: Delete user type
      tags:
      - User Types
    put:
      consumes:
      - application/json
      description: Update user type
      parameters:
      - description: user type id
        in: path
        name: userTypeId
        required: true
        type: string
      - description: Update user type body
        in: body
        name: updateUserTypeBody
        required: true
        schema:
          $ref: '#/definitions/domain.UpdateUserTypeBody'
      produces:
      - application/json
      responses:
        "200":
          description: Success Request
          schema:
            $ref: '#/definitions/httpResponse.StatusResult'
        "500":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorDomain.SmartError'
      security:
      - BearerAuth: []
      summary: Update user type
      tags:
      - User Types
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
