kind: Service
apiVersion: v1
metadata:
  name: roles-core-smartone-api-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: roles-core-smartone
  ports:
    - protocol: TCP
      port: 9006
      targetPort: 80
  type: NodePort
