// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package stores

import (
	context "context"
	domain "gitlab.smartcitiesperu.com/smartone/api-core/stores/domain"

	mock "github.com/stretchr/testify/mock"

	paramsdomain "gitlab.smartcitiesperu.com/smartone/api-shared/params/domain"
)

// StoreRepository is an autogenerated mock type for the StoreRepository type
type StoreRepository struct {
	mock.Mock
}

// CreateStore provides a mock function with given fields: ctx, merchantId, storeId, body
func (_m *StoreRepository) CreateStore(ctx context.Context, merchantId string, storeId string, body domain.CreateStoreBody) (*string, error) {
	ret := _m.Called(ctx, merchantId, storeId, body)

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.CreateStoreBody) (*string, error)); ok {
		return rf(ctx, merchantId, storeId, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.CreateStoreBody) *string); ok {
		r0 = rf(ctx, merchantId, storeId, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, domain.CreateStoreBody) error); ok {
		r1 = rf(ctx, merchantId, storeId, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteStore provides a mock function with given fields: ctx, merchantId, storeId
func (_m *StoreRepository) DeleteStore(ctx context.Context, merchantId string, storeId string) (bool, error) {
	ret := _m.Called(ctx, merchantId, storeId)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, merchantId, storeId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, merchantId, storeId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, merchantId, storeId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStores provides a mock function with given fields: ctx, merchantId, pagination
func (_m *StoreRepository) GetStores(ctx context.Context, merchantId string, pagination paramsdomain.PaginationParams) ([]domain.Store, error) {
	ret := _m.Called(ctx, merchantId, pagination)

	var r0 []domain.Store
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, paramsdomain.PaginationParams) ([]domain.Store, error)); ok {
		return rf(ctx, merchantId, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, paramsdomain.PaginationParams) []domain.Store); ok {
		r0 = rf(ctx, merchantId, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Store)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, paramsdomain.PaginationParams) error); ok {
		r1 = rf(ctx, merchantId, pagination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalStores provides a mock function with given fields: ctx, merchantId, pagination
func (_m *StoreRepository) GetTotalStores(ctx context.Context, merchantId string, pagination paramsdomain.PaginationParams) (*int, error) {
	ret := _m.Called(ctx, merchantId, pagination)

	var r0 *int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, paramsdomain.PaginationParams) (*int, error)); ok {
		return rf(ctx, merchantId, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, paramsdomain.PaginationParams) *int); ok {
		r0 = rf(ctx, merchantId, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, paramsdomain.PaginationParams) error); ok {
		r1 = rf(ctx, merchantId, pagination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStore provides a mock function with given fields: ctx, merchantId, storeId, body
func (_m *StoreRepository) UpdateStore(ctx context.Context, merchantId string, storeId string, body domain.CreateStoreBody) error {
	ret := _m.Called(ctx, merchantId, storeId, body)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.CreateStoreBody) error); ok {
		r0 = rf(ctx, merchantId, storeId, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStoreRepository creates a new instance of StoreRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStoreRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StoreRepository {
	mock := &StoreRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
