kind: Service
apiVersion: v1
metadata:
  name: views-core-smartone-api-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: views-core-smartone
  ports:
    - protocol: TCP
      port: 9014
      targetPort: 80
  type: NodePort
