// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package rolePolicies

import (
	context "context"
	domain "gitlab.smartcitiesperu.com/smartone/api-core/role-policies/domain"

	mock "github.com/stretchr/testify/mock"

	paramsdomain "gitlab.smartcitiesperu.com/smartone/api-shared/params/domain"
)

// RolePolicyRepository is an autogenerated mock type for the RolePolicyRepository type
type RolePolicyRepository struct {
	mock.Mock
}

// CreateRolePolicies provides a mock function with given fields: ctx, roleId, body
func (_m *RolePolicyRepository) CreateRolePolicies(ctx context.Context, roleId string, body []domain.CreateMultipleRolePolicyBody) error {
	ret := _m.Called(ctx, roleId, body)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []domain.CreateMultipleRolePolicyBody) error); ok {
		r0 = rf(ctx, roleId, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateRolePolicy provides a mock function with given fields: ctx, rolePolicyId, roleId, body
func (_m *RolePolicyRepository) CreateRolePolicy(ctx context.Context, rolePolicyId string, roleId string, body domain.CreateRolePolicyBody) (*string, error) {
	ret := _m.Called(ctx, rolePolicyId, roleId, body)

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.CreateRolePolicyBody) (*string, error)); ok {
		return rf(ctx, rolePolicyId, roleId, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.CreateRolePolicyBody) *string); ok {
		r0 = rf(ctx, rolePolicyId, roleId, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, domain.CreateRolePolicyBody) error); ok {
		r1 = rf(ctx, rolePolicyId, roleId, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteRolePolicies provides a mock function with given fields: ctx, roleId, rolePolicyIds
func (_m *RolePolicyRepository) DeleteRolePolicies(ctx context.Context, roleId string, rolePolicyIds []string) error {
	ret := _m.Called(ctx, roleId, rolePolicyIds)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, roleId, rolePolicyIds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteRolePolicy provides a mock function with given fields: ctx, roleId, rolePolicyId
func (_m *RolePolicyRepository) DeleteRolePolicy(ctx context.Context, roleId string, rolePolicyId string) (bool, error) {
	ret := _m.Called(ctx, roleId, rolePolicyId)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, roleId, rolePolicyId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, roleId, rolePolicyId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, roleId, rolePolicyId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPolicies provides a mock function with given fields: ctx, searchParams, pagination
func (_m *RolePolicyRepository) GetPolicies(ctx context.Context, searchParams domain.GetRolePoliciesParams, pagination paramsdomain.PaginationParams) ([]domain.RolePolicy, error) {
	ret := _m.Called(ctx, searchParams, pagination)

	var r0 []domain.RolePolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.GetRolePoliciesParams, paramsdomain.PaginationParams) ([]domain.RolePolicy, error)); ok {
		return rf(ctx, searchParams, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.GetRolePoliciesParams, paramsdomain.PaginationParams) []domain.RolePolicy); ok {
		r0 = rf(ctx, searchParams, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.RolePolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.GetRolePoliciesParams, paramsdomain.PaginationParams) error); ok {
		r1 = rf(ctx, searchParams, pagination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalPolicies provides a mock function with given fields: ctx, searchParams, pagination
func (_m *RolePolicyRepository) GetTotalPolicies(ctx context.Context, searchParams domain.GetRolePoliciesParams, pagination paramsdomain.PaginationParams) (*int, error) {
	ret := _m.Called(ctx, searchParams, pagination)

	var r0 *int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.GetRolePoliciesParams, paramsdomain.PaginationParams) (*int, error)); ok {
		return rf(ctx, searchParams, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.GetRolePoliciesParams, paramsdomain.PaginationParams) *int); ok {
		r0 = rf(ctx, searchParams, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.GetRolePoliciesParams, paramsdomain.PaginationParams) error); ok {
		r1 = rf(ctx, searchParams, pagination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRolePolicy provides a mock function with given fields: ctx, roleId, rolePolicyId, body
func (_m *RolePolicyRepository) UpdateRolePolicy(ctx context.Context, roleId string, rolePolicyId string, body domain.UpdateRolePolicyBody) error {
	ret := _m.Called(ctx, roleId, rolePolicyId, body)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.UpdateRolePolicyBody) error); ok {
		r0 = rf(ctx, roleId, rolePolicyId, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyRoleHasPolicy provides a mock function with given fields: ctx, roleId, policyId
func (_m *RolePolicyRepository) VerifyRoleHasPolicy(ctx context.Context, roleId string, policyId string) (bool, error) {
	ret := _m.Called(ctx, roleId, policyId)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, roleId, policyId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, roleId, policyId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, roleId, policyId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRolePolicyRepository creates a new instance of RolePolicyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRolePolicyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RolePolicyRepository {
	mock := &RolePolicyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
