definitions:
  domain.CreateModuleBody:
    properties:
      code:
        description: 'Description: module  code'
        example: logistic
        type: string
      description:
        description: 'Description: module  description'
        example: Modulo de logística
        type: string
      icon:
        description: 'Description: module  icon'
        example: fa fa-chart
        type: string
      name:
        description: 'Description: module  name'
        example: Logistic
        type: string
      position:
        description: 'Description: module  position'
        example: 1
        type: integer
    required:
    - code
    - description
    - icon
    - name
    - position
    type: object
  domain.Module:
    properties:
      code:
        description: 'Description: module  code'
        example: logistic
        type: string
      created_at:
        description: 'Description: module  created_at'
        example: "2023-11-10 08:10:00"
        type: string
      description:
        description: 'Description: module  description'
        example: Modulo de logística
        type: string
      icon:
        description: 'Description: module  icon'
        example: fa fa-chart
        type: string
      id:
        description: 'Description: module  id'
        example: 739bbbc9-7e93-11ee-89fd-0242ac110016
        type: string
      name:
        description: 'Description: module  name'
        example: Logistic
        type: string
      position:
        description: 'Description: module  position'
        example: 1
        type: integer
    required:
    - code
    - description
    - icon
    - id
    - name
    - position
    type: object
  domain.PaginationResults:
    properties:
      current_page:
        type: integer
      from:
        type: integer
      last_page:
        type: integer
      size_page:
        type: integer
      to:
        type: integer
      total:
        type: integer
    required:
    - current_page
    - last_page
    - size_page
    - total
    type: object
  domain.UpdateModuleBody:
    properties:
      code:
        description: 'Description: module  code'
        example: logistic
        type: string
      description:
        description: 'Description: module  description'
        example: Modulo de logística
        type: string
      icon:
        description: 'Description: module  icon'
        example: fa fa-chart
        type: string
      name:
        description: 'Description: module  name'
        example: Logistic
        type: string
      position:
        description: 'Description: module  position'
        example: 1
        type: integer
    required:
    - code
    - description
    - icon
    - name
    - position
    type: object
  errorDomain.LayerErr:
    enum:
    - domain
    - infrastructure
    - interface
    - use_case
    type: string
    x-enum-varnames:
    - Domain
    - Infra
    - Interface
    - UseCase
  errorDomain.LevelErr:
    enum:
    - info
    - warning
    - error
    - fatal
    type: string
    x-enum-varnames:
    - LevelInfo
    - LevelWarning
    - LevelError
    - LevelFatal
  errorDomain.SmartError:
    properties:
      code:
        type: string
      description:
        type: string
      error: {}
      function:
        type: string
      httpStatus:
        type: integer
      layer:
        $ref: '#/definitions/errorDomain.LayerErr'
      level:
        $ref: '#/definitions/errorDomain.LevelErr'
      messages:
        items:
          type: string
        type: array
      raw:
        type: string
    type: object
  httpResponse.IdResult:
    properties:
      data:
        example: "201"
        type: string
      status:
        type: integer
    required:
    - data
    - status
    type: object
  httpResponse.StatusResult:
    properties:
      status:
        example: 200
        type: integer
    required:
    - status
    type: object
  rest.deleteModulesResult:
    properties:
      data:
        type: boolean
      status:
        type: integer
    required:
    - data
    - status
    type: object
  rest.modulesResult:
    properties:
      data:
        items:
          $ref: '#/definitions/domain.Module'
        type: array
      pagination:
        $ref: '#/definitions/domain.PaginationResults'
      status:
        type: integer
    required:
    - data
    - pagination
    - status
    type: object
info:
  contact: {}
paths:
  /api/v1/core/modules:
    get:
      consumes:
      - application/json
      description: Get modules
      parameters:
      - description: Code
        in: query
        name: code
        type: string
      - description: Name
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success Request
          schema:
            $ref: '#/definitions/rest.modulesResult'
        "500":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorDomain.SmartError'
      security:
      - BearerAuth: []
      summary: Get modules
      tags:
      - Modules
    post:
      consumes:
      - application/json
      description: Create module
      parameters:
      - description: Create module body
        in: body
        name: createModuleBody
        required: true
        schema:
          $ref: '#/definitions/domain.CreateModuleBody'
      produces:
      - application/json
      responses:
        "201":
          description: Success Request
          schema:
            $ref: '#/definitions/httpResponse.IdResult'
        "500":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorDomain.SmartError'
      security:
      - BearerAuth: []
      summary: Create module
      tags:
      - Modules
  /api/v1/core/modules/{moduleId}:
    delete:
      consumes:
      - application/json
      description: Delete module
      parameters:
      - description: module id
        in: path
        name: moduleId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success Request
          schema:
            $ref: '#/definitions/rest.deleteModulesResult'
        "500":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorDomain.SmartError'
      security:
      - BearerAuth: []
      summary: Delete module
      tags:
      - Modules
    put:
      consumes:
      - application/json
      description: Update module
      parameters:
      - description: module id
        in: path
        name: moduleId
        required: true
        type: string
      - description: Update module body
        in: body
        name: updateModuleBody
        required: true
        schema:
          $ref: '#/definitions/domain.UpdateModuleBody'
      produces:
      - application/json
      responses:
        "200":
          description: Success Request
          schema:
            $ref: '#/definitions/httpResponse.StatusResult'
        "500":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorDomain.SmartError'
      security:
      - BearerAuth: []
      summary: Update module
      tags:
      - Modules
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
