// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package merchantEconomicActivities

import (
	context "context"
	domain "gitlab.smartcitiesperu.com/smartone/api-core/merchant-economic-activities/domain"

	mock "github.com/stretchr/testify/mock"

	paramsdomain "gitlab.smartcitiesperu.com/smartone/api-shared/params/domain"
)

// MerchantEconomicActivityUseCase is an autogenerated mock type for the MerchantEconomicActivityUseCase type
type MerchantEconomicActivityUseCase struct {
	mock.Mock
}

// CreateEconomicActivity provides a mock function with given fields: ctx, merchantEconomicActivityId, body
func (_m *MerchantEconomicActivityUseCase) CreateEconomicActivity(ctx context.Context, merchantEconomicActivityId string, body domain.CreateMerchantEconomicActivityBody) (*string, error) {
	ret := _m.Called(ctx, merchantEconomicActivityId, body)

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.CreateMerchantEconomicActivityBody) (*string, error)); ok {
		return rf(ctx, merchantEconomicActivityId, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.CreateMerchantEconomicActivityBody) *string); ok {
		r0 = rf(ctx, merchantEconomicActivityId, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.CreateMerchantEconomicActivityBody) error); ok {
		r1 = rf(ctx, merchantEconomicActivityId, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteEconomicActivity provides a mock function with given fields: ctx, merchantEconomicActivityId
func (_m *MerchantEconomicActivityUseCase) DeleteEconomicActivity(ctx context.Context, merchantEconomicActivityId string) (bool, error) {
	ret := _m.Called(ctx, merchantEconomicActivityId)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, merchantEconomicActivityId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, merchantEconomicActivityId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchantEconomicActivityId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMerchantEconomicActivities provides a mock function with given fields: ctx, merchantId, pagination
func (_m *MerchantEconomicActivityUseCase) GetMerchantEconomicActivities(ctx context.Context, merchantId string, pagination paramsdomain.PaginationParams) ([]domain.MerchantEconomicActivity, *paramsdomain.PaginationResults, error) {
	ret := _m.Called(ctx, merchantId, pagination)

	var r0 []domain.MerchantEconomicActivity
	var r1 *paramsdomain.PaginationResults
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, paramsdomain.PaginationParams) ([]domain.MerchantEconomicActivity, *paramsdomain.PaginationResults, error)); ok {
		return rf(ctx, merchantId, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, paramsdomain.PaginationParams) []domain.MerchantEconomicActivity); ok {
		r0 = rf(ctx, merchantId, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MerchantEconomicActivity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, paramsdomain.PaginationParams) *paramsdomain.PaginationResults); ok {
		r1 = rf(ctx, merchantId, pagination)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*paramsdomain.PaginationResults)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, paramsdomain.PaginationParams) error); ok {
		r2 = rf(ctx, merchantId, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateEconomicActivity provides a mock function with given fields: ctx, merchantEconomicActivityId, body
func (_m *MerchantEconomicActivityUseCase) UpdateEconomicActivity(ctx context.Context, merchantEconomicActivityId string, body domain.UpdateMerchantEconomicActivityBody) error {
	ret := _m.Called(ctx, merchantEconomicActivityId, body)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.UpdateMerchantEconomicActivityBody) error); ok {
		r0 = rf(ctx, merchantEconomicActivityId, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMerchantEconomicActivityUseCase creates a new instance of MerchantEconomicActivityUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMerchantEconomicActivityUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MerchantEconomicActivityUseCase {
	mock := &MerchantEconomicActivityUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
