// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package permissions

import (
	context "context"
	domain "gitlab.smartcitiesperu.com/smartone/api-core/permissions/domain"

	mock "github.com/stretchr/testify/mock"

	paramsdomain "gitlab.smartcitiesperu.com/smartone/api-shared/params/domain"
)

// PermissionUseCase is an autogenerated mock type for the PermissionUseCase type
type PermissionUseCase struct {
	mock.Mock
}

// CreatePermission provides a mock function with given fields: ctx, moduleId, body
func (_m *PermissionUseCase) CreatePermission(ctx context.Context, moduleId string, body domain.CreatePermissionBody) (*string, error) {
	ret := _m.Called(ctx, moduleId, body)

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.CreatePermissionBody) (*string, error)); ok {
		return rf(ctx, moduleId, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.CreatePermissionBody) *string); ok {
		r0 = rf(ctx, moduleId, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.CreatePermissionBody) error); ok {
		r1 = rf(ctx, moduleId, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeletePermission provides a mock function with given fields: ctx, moduleId, permissionId
func (_m *PermissionUseCase) DeletePermission(ctx context.Context, moduleId string, permissionId string) (bool, error) {
	ret := _m.Called(ctx, moduleId, permissionId)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, moduleId, permissionId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, moduleId, permissionId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, moduleId, permissionId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPermissions provides a mock function with given fields: ctx, moduleId, searchParams, pagination
func (_m *PermissionUseCase) GetPermissions(ctx context.Context, moduleId string, searchParams domain.GetPermissionsParams, pagination paramsdomain.PaginationParams) ([]domain.Permission, *paramsdomain.PaginationResults, error) {
	ret := _m.Called(ctx, moduleId, searchParams, pagination)

	var r0 []domain.Permission
	var r1 *paramsdomain.PaginationResults
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.GetPermissionsParams, paramsdomain.PaginationParams) ([]domain.Permission, *paramsdomain.PaginationResults, error)); ok {
		return rf(ctx, moduleId, searchParams, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.GetPermissionsParams, paramsdomain.PaginationParams) []domain.Permission); ok {
		r0 = rf(ctx, moduleId, searchParams, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.GetPermissionsParams, paramsdomain.PaginationParams) *paramsdomain.PaginationResults); ok {
		r1 = rf(ctx, moduleId, searchParams, pagination)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*paramsdomain.PaginationResults)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, domain.GetPermissionsParams, paramsdomain.PaginationParams) error); ok {
		r2 = rf(ctx, moduleId, searchParams, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdatePermission provides a mock function with given fields: ctx, moduleId, permissionId, body
func (_m *PermissionUseCase) UpdatePermission(ctx context.Context, moduleId string, permissionId string, body domain.UpdatePermissionBody) error {
	ret := _m.Called(ctx, moduleId, permissionId, body)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.UpdatePermissionBody) error); ok {
		r0 = rf(ctx, moduleId, permissionId, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPermissionUseCase creates a new instance of PermissionUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPermissionUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *PermissionUseCase {
	mock := &PermissionUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
