kind: Service
apiVersion: v1
metadata:
  name: document-types-core-smartone-api-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: document-types-core-smartone
  ports:
    - protocol: TCP
      port: 9017
      targetPort: 80
  type: NodePort
